[files]
extend-exclude = [
  "**/coverage/**",
  "**/node_modules/**",
  "**/target/**",
  "**/dist/**",
  "**/prettify.js"
]

[default]
extend-ignore-re = [
  "lang(?:uage)?-"
]

[default.extend-words]
uage = "uage"
