name: "Release Drafter"

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create and update releases
      pull-requests: write # To add the drafted release notes to the release
    steps:
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify custom config file
        # with:
        #   config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
